### PR TITLE
Several fixes

### PR DESCRIPTION
**Pull request by gastaldi**

### CODE REVIEW

**Comment by rmpestano** [comment]
Hi @gastaldi, many thanks for the PR. I don't know if it was the singleton commands or maven deps but the tests are running much much faster! thanks again!

**Comment by gastaldi** [comment]
It was the dependency to core instead of the individual addons
Em 19/10/2015 21:56, "Rafael M. Pestano" <notifications@github.com>
escreveu:

**Comment by rmpestano** [comment]
Great! Travis build time dropped from 5 min to 2min. Maybe we should have some 'WARNING:' on the docs.

Do you have any hint on #6?

**Comment by gastaldi** [comment]
Not yet. I will think of something. Suggestions are welcome.
Em 19/10/2015 22:05, "Rafael M. Pestano" <notifications@github.com>
escreveu:

**Pull request merged**
